### ISSUE TITLE
Milestone: Hello, world!

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#20]
Cesium should be able to compile a "Hello, world" program. Namely, this one:
```c
#include <stdio.h>
int main(void) 
{
  puts("Hello, world!");
}
```

This is a simple program, yet it has several important features we're currently lacking:
- [x] #21: basic preprocessor requirement (`#include`)
- [x] standard library routine (`<stdio.h>` and `puts`)
  - [x] #22: ability to call to CLI methods
  - [x] #23: implement these methods in the runtime library
- [x] #24: string support
- [ ] #6: standard `main` signature, `int main(void)`

**Comment by kant2002** [comment]
I think you should add at least one milestone. `Functions support`. And within that we should add `data types` support. That's would be easier to test IMO. 

I assume we create custom `stdio.h` which have annotations to call C# functions. so we need functions support first.
IF we create functions we definitely would like to have pointer types support, and look for fancy expressions here. So that's why I think Hello World is slightly far i the future.

**Comment by ForNeVeR** [comment]
I don't believe that "Functions support" is a feature big enough to make a whole "milestone" out of it.

For me, "milestone" is a rough target for the project: doable is a relatively short period of time, and yet significant enough. It doesn't mean any other features are forbidden to implement.

Regarding the data types support: yeah, that's big, but because of its size, I'm not marking it as the first priority for myself right now.
