### ISSUE TITLE
C23 update

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Cesium#441]
Since C23 has been released, we'll need to update our ongoing efforts to target it.

## TODO
- [x] Update the README
- [x] Update/add the preprocessor issues
- [x] Update/add the lexer issues
- [x] Update/add the parser issues
